#GDP Access List forTaiwan 
GDPtable = [{'Country': 'Taiwan',
  'GDP_Access': 579302.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Afghanistan',
  'GDP_Access': 8355.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Albania',
  'GDP_Access': 11700.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Algeria',
  'GDP_Access': 71314.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Andorra',
  'GDP_Access': 2711.7,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Angola',
  'GDP_Access': 49683.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Antigua and Barbuda',
  'GDP_Access': 1381.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Argentina',
  'GDP_Access': 255086.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Armenia',
  'GDP_Access': 7725.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Australia',
  'GDP_Access': 551819.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Austria',
  'GDP_Access': 375160.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Azerbaijan',
  'GDP_Access': 20335.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Bahamas',
  'GDP_Access': 3650.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Bahrain',
  'GDP_Access': 17447.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Bangladesh',
  'GDP_Access': 182961.8,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Barbados',
  'GDP_Access': 1928.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Belarus',
  'GDP_Access': 21774.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Belgium',
  'GDP_Access': 445259.7,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Belize',
  'GDP_Access': 1637.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Benin',
  'GDP_Access': 6587.0,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Bhutan',
  'GDP_Access': 928.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Bolivia',
  'GDP_Access': 25985.4,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Bosnia and Herzegovina',
  'GDP_Access': 15711.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Botswana',
  'GDP_Access': 6690.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Brazil',
  'GDP_Access': 821987.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Brunei',
  'GDP_Access': 8374.1,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Bulgaria',
  'GDP_Access': 51248.7,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Burkina Faso',
  'GDP_Access': 9230.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Burundi',
  'GDP_Access': 1357.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Cambodia',
  'GDP_Access': 15576.4,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Cameroon',
  'GDP_Access': 13602.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Canada',
  'GDP_Access': 826206.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Cape Verde',
  'GDP_Access': 1209.6,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Central African Republic',
  'GDP_Access': 796.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Chad',
  'GDP_Access': 3896.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Chile',
  'GDP_Access': 249337.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'China',
  'GDP_Access': 8410227.0,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Colombia',
  'GDP_Access': 278277.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Comoros',
  'GDP_Access': 461.3,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Republic of the Congo',
  'GDP_Access': 16576.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Democratic Republic of the Congo',
  'GDP_Access': 16576.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Costa Rica',
  'GDP_Access': 52250.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Ivory Coast',
  'GDP_Access': 20180.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Croatia',
  'GDP_Access': 49064.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Cuba',
  'GDP_Access': 35875.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Cyprus',
  'GDP_Access': 19179.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Czech Republic',
  'GDP_Access': 191870.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Denmark',
  'GDP_Access': 292035.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Djibouti',
  'GDP_Access': 1041.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Dominica',
  'GDP_Access': 67516.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Dominican Republic',
  'GDP_Access': 67516.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Ecuador',
  'GDP_Access': 92079.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Egypt',
  'GDP_Access': 165951.1,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'El Salvador',
  'GDP_Access': 25220.7,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Equatorial Guinea',
  'GDP_Access': 4027.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Eritrea',
  'GDP_Access': 2420.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Estonia',
  'GDP_Access': 23375.7,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Ethiopia',
  'GDP_Access': 56611.8,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Fiji',
  'GDP_Access': 4548.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Finland',
  'GDP_Access': 227919.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'France',
  'GDP_Access': 2325204.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Gabon',
  'GDP_Access': 7233.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Gambia',
  'GDP_Access': 934.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Georgia',
  'GDP_Access': 0.0,
  'VisaRequirement': 'Travel not Allowed',
  'VisaTemplate': 'BLACK'},
 {'Country': 'Germany',
  'GDP_Access': 3316334.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Ghana',
  'GDP_Access': 18812.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Greece',
  'GDP_Access': 180621.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Grenada',
  'GDP_Access': 444.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Guatemala',
  'GDP_Access': 68094.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Guinea',
  'GDP_Access': 9446.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Guinea-Bissau',
  'GDP_Access': 6428.1,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Guyana',
  'GDP_Access': 1436.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Haiti',
  'GDP_Access': 7524.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Honduras',
  'GDP_Access': 20677.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Hungary',
  'GDP_Access': 137055.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Iceland',
  'GDP_Access': 21518.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'India',
  'GDP_Access': 1305506.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Indonesia',
  'GDP_Access': 913869.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Iran',
  'GDP_Access': 302344.0,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Iraq',
  'GDP_Access': 79079.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Ireland',
  'GDP_Access': 300594.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Israel',
  'GDP_Access': 315548.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Italy',
  'GDP_Access': 1744104.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Jamaica',
  'GDP_Access': 5716.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Japan',
  'GDP_Access': 4384921.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Jordan',
  'GDP_Access': 28340.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Kazakhstan',
  'GDP_Access': 64335.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Kenya',
  'GDP_Access': 39755.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Kiribati',
  'GDP_Access': 167.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'North Korea',
  'GDP_Access': 6958.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'South Korea',
  'GDP_Access': 1384227.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Kuwait',
  'GDP_Access': 48140.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Kyrgyzstan',
  'GDP_Access': 3530.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Laos',
  'GDP_Access': 12006.4,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Latvia',
  'GDP_Access': 27287.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Lebanon',
  'GDP_Access': 20582.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Lesotho',
  'GDP_Access': 1360.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Liberia',
  'GDP_Access': 856.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Libya',
  'GDP_Access': 12532.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Liechtenstein',
  'GDP_Access': 5269.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Lithuania',
  'GDP_Access': 42536.7,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Luxembourg',
  'GDP_Access': 56153.7,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Macedonia',
  'GDP_Access': 10274.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Madagascar',
  'GDP_Access': 7389.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Malawi',
  'GDP_Access': 4382.7,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Malaysia',
  'GDP_Access': 283047.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Maldives',
  'GDP_Access': 3164.0,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Mali',
  'GDP_Access': 5999.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Malta',
  'GDP_Access': 10809.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Marshall Islands',
  'GDP_Access': 139.3,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Mauritania',
  'GDP_Access': 3489.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Mauritius',
  'GDP_Access': 8591.1,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Mexico',
  'GDP_Access': 459694.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Micronesia',
  'GDP_Access': 296.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Moldova',
  'GDP_Access': 3178.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Monaco',
  'GDP_Access': 6354.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Mongolia',
  'GDP_Access': 4347.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Montenegro',
  'GDP_Access': 3964.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Morocco',
  'GDP_Access': 43929.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Mozambique',
  'GDP_Access': 8641.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Myanmar',
  'GDP_Access': 33268.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Namibia',
  'GDP_Access': 5023.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Nauru',
  'GDP_Access': 102.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Nepal',
  'GDP_Access': 17130.4,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Netherlands',
  'GDP_Access': 743170.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'New Zealand',
  'GDP_Access': 181336.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Nicaragua',
  'GDP_Access': 12322.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Niger',
  'GDP_Access': 150513.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Nigeria',
  'GDP_Access': 150513.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Norway',
  'GDP_Access': 356811.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Oman',
  'GDP_Access': 37137.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Pakistan',
  'GDP_Access': 121597.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Palau',
  'GDP_Access': 224.7,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Panama',
  'GDP_Access': 55654.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Papua New Guinea',
  'GDP_Access': 21255.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Paraguay',
  'GDP_Access': 26657.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Peru',
  'GDP_Access': 193701.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Philippines',
  'GDP_Access': 156709.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Poland',
  'GDP_Access': 472397.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Portugal',
  'GDP_Access': 196257.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Qatar',
  'GDP_Access': 116428.2,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Romania',
  'GDP_Access': 190183.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Russia',
  'GDP_Access': 610987.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Rwanda',
  'GDP_Access': 6242.6,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Saint Kitts and Nevis',
  'GDP_Access': 851.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Saint Lucia',
  'GDP_Access': 1540.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Saint Vincent and the Grenadines',
  'GDP_Access': 711.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Samoa',
  'GDP_Access': 590.8,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'San Marino',
  'GDP_Access': 1432.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Sao Tome and Principe',
  'GDP_Access': 186.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Saudi Arabia',
  'GDP_Access': 273530.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Senegal',
  'GDP_Access': 6422.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Serbia',
  'GDP_Access': 16588.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Seychelles',
  'GDP_Access': 1035.3,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Sierra Leone',
  'GDP_Access': 1558.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Singapore',
  'GDP_Access': 291511.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Slovakia',
  'GDP_Access': 86344.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Slovenia',
  'GDP_Access': 43981.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Solomon Islands',
  'GDP_Access': 891.1,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Somalia',
  'GDP_Access': 5158.3,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'South Africa',
  'GDP_Access': 139719.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'South Sudan',
  'GDP_Access': 23295.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Spain',
  'GDP_Access': 1182555.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Sri Lanka',
  'GDP_Access': 43795.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Sudan',
  'GDP_Access': 23295.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Suriname',
  'GDP_Access': 1466.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Sweden',
  'GDP_Access': 484717.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Switzerland',
  'GDP_Access': 610717.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Syria',
  'GDP_Access': 30984.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Tajikistan',
  'GDP_Access': 3617.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Tanzania',
  'GDP_Access': 36207.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Thailand',
  'GDP_Access': 318764.6,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Timor-Leste',
  'GDP_Access': 1901.2,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Togo',
  'GDP_Access': 3357.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Tonga',
  'GDP_Access': 174.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Trinidad and Tobago',
  'GDP_Access': 8120.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Tunisia',
  'GDP_Access': 16110.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Turkey',
  'GDP_Access': 424740.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Turkmenistan',
  'GDP_Access': 15170.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Tuvalu',
  'GDP_Access': 36.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Uganda',
  'GDP_Access': 18444.3,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Ukraine',
  'GDP_Access': 43728.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'United Arab Emirates',
  'GDP_Access': 150974.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'United Kingdom',
  'GDP_Access': 2362076.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'United States',
  'GDP_Access': 9695300.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Uruguay',
  'GDP_Access': 52573.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Uzbekistan',
  'GDP_Access': 19153.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Vanuatu',
  'GDP_Access': 753.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Venezuela',
  'GDP_Access': 84034.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Vietnam',
  'GDP_Access': 88163.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Yemen',
  'GDP_Access': 6604.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Zambia',
  'GDP_Access': 12752.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Zimbabwe',
  'GDP_Access': 8552.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'}]