#GDP Access List forSierra Leone 
GDPtable = [{'Country': 'Sierra Leone',
  'GDP_Access': 3897.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Afghanistan',
  'GDP_Access': 8355.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Albania',
  'GDP_Access': 5200.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Algeria',
  'GDP_Access': 71314.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Andorra',
  'GDP_Access': 1205.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Angola',
  'GDP_Access': 49683.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Antigua and Barbuda',
  'GDP_Access': 767.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Argentina',
  'GDP_Access': 255086.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Armenia',
  'GDP_Access': 4414.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Australia',
  'GDP_Access': 551819.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Austria',
  'GDP_Access': 166738.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Azerbaijan',
  'GDP_Access': 16268.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Bahamas',
  'GDP_Access': 8214.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Bahrain',
  'GDP_Access': 13958.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Bangladesh',
  'GDP_Access': 235236.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Barbados',
  'GDP_Access': 4338.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Belarus',
  'GDP_Access': 21774.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Belgium',
  'GDP_Access': 197893.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Belize',
  'GDP_Access': 1637.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Benin',
  'GDP_Access': 8469.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Bhutan',
  'GDP_Access': 928.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Bolivia',
  'GDP_Access': 25985.4,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Bosnia and Herzegovina',
  'GDP_Access': 6982.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Botswana',
  'GDP_Access': 15052.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Brazil',
  'GDP_Access': 821987.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Brunei',
  'GDP_Access': 4785.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Bulgaria',
  'GDP_Access': 22777.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Burkina Faso',
  'GDP_Access': 11868.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Burundi',
  'GDP_Access': 1357.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Cambodia',
  'GDP_Access': 15576.4,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Cameroon',
  'GDP_Access': 13602.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Canada',
  'GDP_Access': 660964.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Cape Verde',
  'GDP_Access': 1555.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Central African Republic',
  'GDP_Access': 796.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Chad',
  'GDP_Access': 3896.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Chile',
  'GDP_Access': 110816.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'China',
  'GDP_Access': 4805844.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Colombia',
  'GDP_Access': 123678.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Comoros',
  'GDP_Access': 461.3,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Republic of the Congo',
  'GDP_Access': 16576.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Democratic Republic of the Congo',
  'GDP_Access': 16576.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Costa Rica',
  'GDP_Access': 23222.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Ivory Coast',
  'GDP_Access': 36324.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Croatia',
  'GDP_Access': 21806.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Cuba',
  'GDP_Access': 35875.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Cyprus',
  'GDP_Access': 8524.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Czech Republic',
  'GDP_Access': 85275.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Denmark',
  'GDP_Access': 129793.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Djibouti',
  'GDP_Access': 1041.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Dominica',
  'GDP_Access': 67516.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Dominican Republic',
  'GDP_Access': 30007.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Ecuador',
  'GDP_Access': 92079.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Egypt',
  'GDP_Access': 94829.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'El Salvador',
  'GDP_Access': 11209.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Equatorial Guinea',
  'GDP_Access': 4027.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Eritrea',
  'GDP_Access': 2420.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Estonia',
  'GDP_Access': 10389.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Ethiopia',
  'GDP_Access': 56611.8,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Fiji',
  'GDP_Access': 4548.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Finland',
  'GDP_Access': 101297.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'France',
  'GDP_Access': 1033424.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Gabon',
  'GDP_Access': 7233.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Gambia',
  'GDP_Access': 934.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Georgia',
  'GDP_Access': 6092.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Germany',
  'GDP_Access': 1473926.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Ghana',
  'GDP_Access': 42328.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Greece',
  'GDP_Access': 80276.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Grenada',
  'GDP_Access': 999.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Guatemala',
  'GDP_Access': 30264.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Guinea',
  'GDP_Access': 21255.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Guinea-Bissau',
  'GDP_Access': 8264.7,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Guyana',
  'GDP_Access': 1436.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Haiti',
  'GDP_Access': 7524.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Honduras',
  'GDP_Access': 9190.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Hungary',
  'GDP_Access': 60913.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Iceland',
  'GDP_Access': 9563.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'India',
  'GDP_Access': 1305506.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Indonesia',
  'GDP_Access': 406164.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Iran',
  'GDP_Access': 302344.0,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Iraq',
  'GDP_Access': 79079.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Ireland',
  'GDP_Access': 133597.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Israel',
  'GDP_Access': 140243.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Italy',
  'GDP_Access': 775157.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Jamaica',
  'GDP_Access': 12861.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Japan',
  'GDP_Access': 1948854.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Jordan',
  'GDP_Access': 16194.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Kazakhstan',
  'GDP_Access': 64335.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Kenya',
  'GDP_Access': 71559.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Kiribati',
  'GDP_Access': 167.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'North Korea',
  'GDP_Access': 6958.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'South Korea',
  'GDP_Access': 615212.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Kuwait',
  'GDP_Access': 48140.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Kyrgyzstan',
  'GDP_Access': 3530.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Laos',
  'GDP_Access': 6860.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Latvia',
  'GDP_Access': 12127.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Lebanon',
  'GDP_Access': 20582.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Lesotho',
  'GDP_Access': 2448.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Liberia',
  'GDP_Access': 1926.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Libya',
  'GDP_Access': 12532.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Liechtenstein',
  'GDP_Access': 2342.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Lithuania',
  'GDP_Access': 18905.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Luxembourg',
  'GDP_Access': 24957.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Macedonia',
  'GDP_Access': 4566.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Madagascar',
  'GDP_Access': 7389.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Malawi',
  'GDP_Access': 4382.7,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Malaysia',
  'GDP_Access': 283047.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Maldives',
  'GDP_Access': 3164.0,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Mali',
  'GDP_Access': 13498.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Malta',
  'GDP_Access': 4804.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Marshall Islands',
  'GDP_Access': 79.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Mauritania',
  'GDP_Access': 3489.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Mauritius',
  'GDP_Access': 11045.7,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Mexico',
  'GDP_Access': 459694.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Micronesia',
  'GDP_Access': 296.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Moldova',
  'GDP_Access': 3178.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Monaco',
  'GDP_Access': 2824.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Mongolia',
  'GDP_Access': 4347.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Montenegro',
  'GDP_Access': 1762.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Morocco',
  'GDP_Access': 43929.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Mozambique',
  'GDP_Access': 8641.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Myanmar',
  'GDP_Access': 26614.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Namibia',
  'GDP_Access': 5023.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Nauru',
  'GDP_Access': 45.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Nepal',
  'GDP_Access': 17130.4,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Netherlands',
  'GDP_Access': 330298.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'New Zealand',
  'GDP_Access': 80594.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Nicaragua',
  'GDP_Access': 5476.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Niger',
  'GDP_Access': 338655.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Nigeria',
  'GDP_Access': 338655.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Norway',
  'GDP_Access': 158582.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Oman',
  'GDP_Access': 29709.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Pakistan',
  'GDP_Access': 121597.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Palau',
  'GDP_Access': 224.7,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Panama',
  'GDP_Access': 24735.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Papua New Guinea',
  'GDP_Access': 9446.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Paraguay',
  'GDP_Access': 11847.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Peru',
  'GDP_Access': 86089.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Philippines',
  'GDP_Access': 125367.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Poland',
  'GDP_Access': 209954.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Portugal',
  'GDP_Access': 87225.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Qatar',
  'GDP_Access': 66530.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Romania',
  'GDP_Access': 84526.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Russia',
  'GDP_Access': 610987.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Rwanda',
  'GDP_Access': 6242.6,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Saint Kitts and Nevis',
  'GDP_Access': 851.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Saint Lucia',
  'GDP_Access': 1198.4,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Saint Vincent and the Grenadines',
  'GDP_Access': 711.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Samoa',
  'GDP_Access': 590.8,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'San Marino',
  'GDP_Access': 636.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Sao Tome and Principe',
  'GDP_Access': 186.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Saudi Arabia',
  'GDP_Access': 273530.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Senegal',
  'GDP_Access': 14451.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Serbia',
  'GDP_Access': 16588.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Seychelles',
  'GDP_Access': 1331.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Singapore',
  'GDP_Access': 291511.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Slovakia',
  'GDP_Access': 38375.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Slovenia',
  'GDP_Access': 19547.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Solomon Islands',
  'GDP_Access': 509.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Somalia',
  'GDP_Access': 5158.3,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'South Africa',
  'GDP_Access': 139719.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'South Sudan',
  'GDP_Access': 23295.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Spain',
  'GDP_Access': 525580.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Sri Lanka',
  'GDP_Access': 35036.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Sudan',
  'GDP_Access': 40767.3,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Suriname',
  'GDP_Access': 1466.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Sweden',
  'GDP_Access': 215430.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Switzerland',
  'GDP_Access': 271430.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Syria',
  'GDP_Access': 30984.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Tajikistan',
  'GDP_Access': 2893.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Tanzania',
  'GDP_Access': 20690.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Thailand',
  'GDP_Access': 182151.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Timor-Leste',
  'GDP_Access': 1901.2,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Togo',
  'GDP_Access': 4317.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Tonga',
  'GDP_Access': 174.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Trinidad and Tobago',
  'GDP_Access': 18270.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Tunisia',
  'GDP_Access': 16110.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Turkey',
  'GDP_Access': 339792.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Turkmenistan',
  'GDP_Access': 15170.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Tuvalu',
  'GDP_Access': 28.0,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Uganda',
  'GDP_Access': 23714.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Ukraine',
  'GDP_Access': 43728.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'United Arab Emirates',
  'GDP_Access': 150974.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'United Kingdom',
  'GDP_Access': 1049811.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'United States',
  'GDP_Access': 7756240.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Uruguay',
  'GDP_Access': 23366.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Uzbekistan',
  'GDP_Access': 19153.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Vanuatu',
  'GDP_Access': 753.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Venezuela',
  'GDP_Access': 84034.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Vietnam',
  'GDP_Access': 88163.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Yemen',
  'GDP_Access': 6604.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Zambia',
  'GDP_Access': 10201.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Zimbabwe',
  'GDP_Access': 6842.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'}]