#GDP Access List forEcuador 
GDPtable = [{'Country': 'Ecuador',
  'GDP_Access': 102311.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Afghanistan',
  'GDP_Access': 8355.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Albania',
  'GDP_Access': 5200.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Algeria',
  'GDP_Access': 71314.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Andorra',
  'GDP_Access': 1205.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Angola',
  'GDP_Access': 49683.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Antigua and Barbuda',
  'GDP_Access': 767.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Argentina',
  'GDP_Access': 573945.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Armenia',
  'GDP_Access': 7725.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Australia',
  'GDP_Access': 551819.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Austria',
  'GDP_Access': 166738.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Azerbaijan',
  'GDP_Access': 20335.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Bahamas',
  'GDP_Access': 8214.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Bahrain',
  'GDP_Access': 24426.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Bangladesh',
  'GDP_Access': 182961.8,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Barbados',
  'GDP_Access': 1928.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Belarus',
  'GDP_Access': 48992.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Belgium',
  'GDP_Access': 197893.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Belize',
  'GDP_Access': 1637.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Benin',
  'GDP_Access': 6587.0,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Bhutan',
  'GDP_Access': 928.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Bolivia',
  'GDP_Access': 33409.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Bosnia and Herzegovina',
  'GDP_Access': 6982.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Botswana',
  'GDP_Access': 6690.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Brazil',
  'GDP_Access': 1849472.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Brunei',
  'GDP_Access': 4785.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Bulgaria',
  'GDP_Access': 22777.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Burkina Faso',
  'GDP_Access': 9230.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Burundi',
  'GDP_Access': 1357.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Cambodia',
  'GDP_Access': 15576.4,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Cameroon',
  'GDP_Access': 13602.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Canada',
  'GDP_Access': 660964.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Cape Verde',
  'GDP_Access': 1209.6,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Central African Republic',
  'GDP_Access': 796.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Chad',
  'GDP_Access': 3896.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Chile',
  'GDP_Access': 249337.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'China',
  'GDP_Access': 10813149.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Colombia',
  'GDP_Access': 278277.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Comoros',
  'GDP_Access': 461.3,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Republic of the Congo',
  'GDP_Access': 16576.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Democratic Republic of the Congo',
  'GDP_Access': 16576.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Costa Rica',
  'GDP_Access': 23222.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Ivory Coast',
  'GDP_Access': 16144.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Croatia',
  'GDP_Access': 21806.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Cuba',
  'GDP_Access': 35875.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Cyprus',
  'GDP_Access': 8524.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Czech Republic',
  'GDP_Access': 85275.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Denmark',
  'GDP_Access': 129793.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Djibouti',
  'GDP_Access': 1041.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Dominica',
  'GDP_Access': 67516.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Dominican Republic',
  'GDP_Access': 67516.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Egypt',
  'GDP_Access': 165951.1,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'El Salvador',
  'GDP_Access': 25220.7,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Equatorial Guinea',
  'GDP_Access': 4027.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Eritrea',
  'GDP_Access': 2420.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Estonia',
  'GDP_Access': 10389.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Ethiopia',
  'GDP_Access': 40437.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Fiji',
  'GDP_Access': 2021.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Finland',
  'GDP_Access': 101297.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'France',
  'GDP_Access': 1033424.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Gabon',
  'GDP_Access': 7233.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Gambia',
  'GDP_Access': 415.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Georgia',
  'GDP_Access': 13707.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Germany',
  'GDP_Access': 1473926.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Ghana',
  'GDP_Access': 18812.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Greece',
  'GDP_Access': 80276.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Grenada',
  'GDP_Access': 444.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Guatemala',
  'GDP_Access': 30264.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Guinea',
  'GDP_Access': 9446.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Guinea-Bissau',
  'GDP_Access': 6428.1,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Guyana',
  'GDP_Access': 3231.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Haiti',
  'GDP_Access': 7524.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Honduras',
  'GDP_Access': 20677.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Hungary',
  'GDP_Access': 60913.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Iceland',
  'GDP_Access': 9563.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'India',
  'GDP_Access': 1305506.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Indonesia',
  'GDP_Access': 913869.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Iran',
  'GDP_Access': 302344.0,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Iraq',
  'GDP_Access': 79079.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Ireland',
  'GDP_Access': 133597.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Israel',
  'GDP_Access': 315548.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Italy',
  'GDP_Access': 775157.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Jamaica',
  'GDP_Access': 12861.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Japan',
  'GDP_Access': 1948854.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Jordan',
  'GDP_Access': 28340.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Kazakhstan',
  'GDP_Access': 144755.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Kenya',
  'GDP_Access': 55657.7,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Kiribati',
  'GDP_Access': 74.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'North Korea',
  'GDP_Access': 6958.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'South Korea',
  'GDP_Access': 1384227.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Kuwait',
  'GDP_Access': 48140.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Kyrgyzstan',
  'GDP_Access': 3530.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Laos',
  'GDP_Access': 12006.4,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Latvia',
  'GDP_Access': 12127.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Lebanon',
  'GDP_Access': 20582.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Lesotho',
  'GDP_Access': 1360.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Liberia',
  'GDP_Access': 856.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Libya',
  'GDP_Access': 12532.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Liechtenstein',
  'GDP_Access': 2342.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Lithuania',
  'GDP_Access': 18905.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Luxembourg',
  'GDP_Access': 24957.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Macedonia',
  'GDP_Access': 4566.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Madagascar',
  'GDP_Access': 7389.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Malawi',
  'GDP_Access': 4382.7,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Malaysia',
  'GDP_Access': 283047.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Maldives',
  'GDP_Access': 3164.0,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Mali',
  'GDP_Access': 5999.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Malta',
  'GDP_Access': 4804.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Marshall Islands',
  'GDP_Access': 79.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Mauritania',
  'GDP_Access': 3489.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Mauritius',
  'GDP_Access': 8591.1,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Mexico',
  'GDP_Access': 459694.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Micronesia',
  'GDP_Access': 296.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Moldova',
  'GDP_Access': 7150.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Monaco',
  'GDP_Access': 2824.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Mongolia',
  'GDP_Access': 4347.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Montenegro',
  'GDP_Access': 3964.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Morocco',
  'GDP_Access': 43929.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Mozambique',
  'GDP_Access': 8641.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Myanmar',
  'GDP_Access': 33268.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Namibia',
  'GDP_Access': 5023.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Nauru',
  'GDP_Access': 45.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Nepal',
  'GDP_Access': 17130.4,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Netherlands',
  'GDP_Access': 330298.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'New Zealand',
  'GDP_Access': 80594.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Nicaragua',
  'GDP_Access': 12322.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Niger',
  'GDP_Access': 150513.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Nigeria',
  'GDP_Access': 150513.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Norway',
  'GDP_Access': 158582.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Oman',
  'GDP_Access': 37137.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Pakistan',
  'GDP_Access': 121597.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Palau',
  'GDP_Access': 224.7,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Panama',
  'GDP_Access': 55654.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Papua New Guinea',
  'GDP_Access': 16531.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Paraguay',
  'GDP_Access': 26657.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Peru',
  'GDP_Access': 193701.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Philippines',
  'GDP_Access': 282077.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Poland',
  'GDP_Access': 209954.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Portugal',
  'GDP_Access': 87225.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Qatar',
  'GDP_Access': 149693.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Romania',
  'GDP_Access': 84526.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Russia',
  'GDP_Access': 1374722.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Rwanda',
  'GDP_Access': 6242.6,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Saint Kitts and Nevis',
  'GDP_Access': 851.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Saint Lucia',
  'GDP_Access': 1198.4,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Saint Vincent and the Grenadines',
  'GDP_Access': 711.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Samoa',
  'GDP_Access': 590.8,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'San Marino',
  'GDP_Access': 636.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Sao Tome and Principe',
  'GDP_Access': 186.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Saudi Arabia',
  'GDP_Access': 273530.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Senegal',
  'GDP_Access': 6422.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Serbia',
  'GDP_Access': 16588.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Seychelles',
  'GDP_Access': 1035.3,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Sierra Leone',
  'GDP_Access': 1558.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Singapore',
  'GDP_Access': 291511.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Slovakia',
  'GDP_Access': 38375.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Slovenia',
  'GDP_Access': 19547.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Solomon Islands',
  'GDP_Access': 891.1,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Somalia',
  'GDP_Access': 5158.3,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'South Africa',
  'GDP_Access': 314369.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'South Sudan',
  'GDP_Access': 23295.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Spain',
  'GDP_Access': 525580.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Sri Lanka',
  'GDP_Access': 61313.7,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Sudan',
  'GDP_Access': 23295.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Suriname',
  'GDP_Access': 2565.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Sweden',
  'GDP_Access': 215430.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Switzerland',
  'GDP_Access': 271430.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Syria',
  'GDP_Access': 30984.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Tajikistan',
  'GDP_Access': 3617.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Tanzania',
  'GDP_Access': 36207.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Thailand',
  'GDP_Access': 182151.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Timor-Leste',
  'GDP_Access': 1901.2,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Togo',
  'GDP_Access': 3357.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Tonga',
  'GDP_Access': 174.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Trinidad and Tobago',
  'GDP_Access': 18270.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Tunisia',
  'GDP_Access': 16110.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Turkey',
  'GDP_Access': 764532.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Turkmenistan',
  'GDP_Access': 15170.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Tuvalu',
  'GDP_Access': 28.0,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Uganda',
  'GDP_Access': 18444.3,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Ukraine',
  'GDP_Access': 43728.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'United Arab Emirates',
  'GDP_Access': 150974.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'United Kingdom',
  'GDP_Access': 1049811.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'United States',
  'GDP_Access': 7756240.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Uruguay',
  'GDP_Access': 52573.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Uzbekistan',
  'GDP_Access': 19153.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Vanuatu',
  'GDP_Access': 753.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Venezuela',
  'GDP_Access': 189076.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Vietnam',
  'GDP_Access': 88163.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Yemen',
  'GDP_Access': 6604.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Zambia',
  'GDP_Access': 17852.8,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Zimbabwe',
  'GDP_Access': 11973.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'}]