#GDP Access List forCzech Republic 
GDPtable = [{'Country': 'Czech Republic',
  'GDP_Access': 213189.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Afghanistan',
  'GDP_Access': 8355.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Albania',
  'GDP_Access': 11700.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Algeria',
  'GDP_Access': 71314.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Andorra',
  'GDP_Access': 2711.7,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Angola',
  'GDP_Access': 62104.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Antigua and Barbuda',
  'GDP_Access': 1381.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Argentina',
  'GDP_Access': 573945.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Armenia',
  'GDP_Access': 9933.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Australia',
  'GDP_Access': 1241593.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Austria',
  'GDP_Access': 416845.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Azerbaijan',
  'GDP_Access': 20335.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Bahamas',
  'GDP_Access': 8214.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Bahrain',
  'GDP_Access': 24426.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Bangladesh',
  'GDP_Access': 182961.8,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Barbados',
  'GDP_Access': 4338.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Belarus',
  'GDP_Access': 48992.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Belgium',
  'GDP_Access': 494733.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Belize',
  'GDP_Access': 1637.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Benin',
  'GDP_Access': 6587.0,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Bhutan',
  'GDP_Access': 928.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Bolivia',
  'GDP_Access': 33409.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Bosnia and Herzegovina',
  'GDP_Access': 15711.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Botswana',
  'GDP_Access': 15052.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Brazil',
  'GDP_Access': 1849472.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Brunei',
  'GDP_Access': 10766.7,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Bulgaria',
  'GDP_Access': 56943.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Burkina Faso',
  'GDP_Access': 9230.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Burundi',
  'GDP_Access': 1357.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Cambodia',
  'GDP_Access': 15576.4,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Cameroon',
  'GDP_Access': 13602.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Canada',
  'GDP_Access': 1487170.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Cape Verde',
  'GDP_Access': 1209.6,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Central African Republic',
  'GDP_Access': 796.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Chad',
  'GDP_Access': 3896.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Chile',
  'GDP_Access': 249337.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'China',
  'GDP_Access': 4805844.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Colombia',
  'GDP_Access': 278277.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Comoros',
  'GDP_Access': 461.3,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Republic of the Congo',
  'GDP_Access': 16576.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Democratic Republic of the Congo',
  'GDP_Access': 16576.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Costa Rica',
  'GDP_Access': 52250.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Ivory Coast',
  'GDP_Access': 20180.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Croatia',
  'GDP_Access': 54516.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Cuba',
  'GDP_Access': 35875.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Cyprus',
  'GDP_Access': 21310.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Denmark',
  'GDP_Access': 324484.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Djibouti',
  'GDP_Access': 1041.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Dominica',
  'GDP_Access': 67516.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Dominican Republic',
  'GDP_Access': 67516.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Ecuador',
  'GDP_Access': 92079.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Egypt',
  'GDP_Access': 165951.1,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'El Salvador',
  'GDP_Access': 25220.7,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Equatorial Guinea',
  'GDP_Access': 4027.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Eritrea',
  'GDP_Access': 2420.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Estonia',
  'GDP_Access': 25973.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Ethiopia',
  'GDP_Access': 56611.8,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Fiji',
  'GDP_Access': 4548.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Finland',
  'GDP_Access': 253244.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'France',
  'GDP_Access': 2583560.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Gabon',
  'GDP_Access': 10126.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Gambia',
  'GDP_Access': 415.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Georgia',
  'GDP_Access': 13707.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Germany',
  'GDP_Access': 3684816.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Ghana',
  'GDP_Access': 18812.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Greece',
  'GDP_Access': 200690.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Grenada',
  'GDP_Access': 999.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Guatemala',
  'GDP_Access': 68094.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Guinea',
  'GDP_Access': 9446.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Guinea-Bissau',
  'GDP_Access': 6428.1,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Guyana',
  'GDP_Access': 1436.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Haiti',
  'GDP_Access': 7524.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Honduras',
  'GDP_Access': 20677.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Hungary',
  'GDP_Access': 152284.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Iceland',
  'GDP_Access': 23909.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'India',
  'GDP_Access': 1305506.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Indonesia',
  'GDP_Access': 913869.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Iran',
  'GDP_Access': 302344.0,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Iraq',
  'GDP_Access': 79079.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Ireland',
  'GDP_Access': 333994.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Israel',
  'GDP_Access': 315548.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Italy',
  'GDP_Access': 1937894.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Jamaica',
  'GDP_Access': 12861.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Japan',
  'GDP_Access': 4384921.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Jordan',
  'GDP_Access': 28340.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Kazakhstan',
  'GDP_Access': 144755.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Kenya',
  'GDP_Access': 55657.7,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Kiribati',
  'GDP_Access': 167.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'North Korea',
  'GDP_Access': 6958.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'South Korea',
  'GDP_Access': 1384227.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Kuwait',
  'GDP_Access': 84245.7,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Kyrgyzstan',
  'GDP_Access': 6354.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Laos',
  'GDP_Access': 12006.4,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Latvia',
  'GDP_Access': 30319.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Lebanon',
  'GDP_Access': 36019.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Lesotho',
  'GDP_Access': 2448.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Liberia',
  'GDP_Access': 856.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Libya',
  'GDP_Access': 12532.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Liechtenstein',
  'GDP_Access': 5855.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Lithuania',
  'GDP_Access': 47263.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Luxembourg',
  'GDP_Access': 62393.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Macedonia',
  'GDP_Access': 10274.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Madagascar',
  'GDP_Access': 9501.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Malawi',
  'GDP_Access': 4382.7,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Malaysia',
  'GDP_Access': 283047.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Maldives',
  'GDP_Access': 4068.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Mali',
  'GDP_Access': 5999.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Malta',
  'GDP_Access': 12011.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Marshall Islands',
  'GDP_Access': 179.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Mauritania',
  'GDP_Access': 3489.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Mauritius',
  'GDP_Access': 11045.7,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Mexico',
  'GDP_Access': 1034312.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Micronesia',
  'GDP_Access': 296.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Moldova',
  'GDP_Access': 7150.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Monaco',
  'GDP_Access': 6354.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Mongolia',
  'GDP_Access': 4347.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Montenegro',
  'GDP_Access': 3964.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Morocco',
  'GDP_Access': 98841.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Mozambique',
  'GDP_Access': 8641.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Myanmar',
  'GDP_Access': 33268.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Namibia',
  'GDP_Access': 5023.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Nauru',
  'GDP_Access': 45.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Nepal',
  'GDP_Access': 17130.4,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Netherlands',
  'GDP_Access': 825745.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'New Zealand',
  'GDP_Access': 181336.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Nicaragua',
  'GDP_Access': 12322.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Niger',
  'GDP_Access': 150513.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Nigeria',
  'GDP_Access': 150513.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Norway',
  'GDP_Access': 396457.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Oman',
  'GDP_Access': 37137.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Pakistan',
  'GDP_Access': 121597.2,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Palau',
  'GDP_Access': 288.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Panama',
  'GDP_Access': 55654.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Papua New Guinea',
  'GDP_Access': 21255.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Paraguay',
  'GDP_Access': 26657.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Peru',
  'GDP_Access': 193701.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Philippines',
  'GDP_Access': 282077.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Poland',
  'GDP_Access': 524886.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Portugal',
  'GDP_Access': 218064.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Qatar',
  'GDP_Access': 149693.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Romania',
  'GDP_Access': 211315.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Russia',
  'GDP_Access': 610987.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Rwanda',
  'GDP_Access': 6242.6,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Saint Kitts and Nevis',
  'GDP_Access': 851.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Saint Lucia',
  'GDP_Access': 1540.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Saint Vincent and the Grenadines',
  'GDP_Access': 711.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Samoa',
  'GDP_Access': 759.6,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'San Marino',
  'GDP_Access': 1432.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Sao Tome and Principe',
  'GDP_Access': 334.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Saudi Arabia',
  'GDP_Access': 273530.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Senegal',
  'GDP_Access': 14451.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Serbia',
  'GDP_Access': 37323.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Seychelles',
  'GDP_Access': 1331.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Sierra Leone',
  'GDP_Access': 1558.8,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Singapore',
  'GDP_Access': 291511.8,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Slovakia',
  'GDP_Access': 95938.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Slovenia',
  'GDP_Access': 48868.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Solomon Islands',
  'GDP_Access': 1145.7,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Somalia',
  'GDP_Access': 5158.3,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'South Africa',
  'GDP_Access': 314369.1,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'South Sudan',
  'GDP_Access': 23295.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Spain',
  'GDP_Access': 1313951.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Sri Lanka',
  'GDP_Access': 61313.7,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Sudan',
  'GDP_Access': 23295.6,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Suriname',
  'GDP_Access': 2565.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Sweden',
  'GDP_Access': 538575.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Switzerland',
  'GDP_Access': 678575.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'Syria',
  'GDP_Access': 30984.0,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Tajikistan',
  'GDP_Access': 3617.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Tanzania',
  'GDP_Access': 36207.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Thailand',
  'GDP_Access': 409840.2,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Timor-Leste',
  'GDP_Access': 2444.4,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Togo',
  'GDP_Access': 3357.9,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'yes-no'},
 {'Country': 'Tonga',
  'GDP_Access': 393.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Trinidad and Tobago',
  'GDP_Access': 18270.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Tunisia',
  'GDP_Access': 36247.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Turkey',
  'GDP_Access': 764532.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Turkmenistan',
  'GDP_Access': 15170.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Tuvalu',
  'GDP_Access': 36.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Uganda',
  'GDP_Access': 18444.3,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Ukraine',
  'GDP_Access': 98388.9,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'United Arab Emirates',
  'GDP_Access': 339691.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'United Kingdom',
  'GDP_Access': 2624529.0,
  'VisaRequirement': 'Freedom of Movement',
  'VisaTemplate': 'free'},
 {'Country': 'United States',
  'GDP_Access': 17451540.0,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Uruguay',
  'GDP_Access': 52573.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Uzbekistan',
  'GDP_Access': 23941.5,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Vanuatu',
  'GDP_Access': 753.3,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Venezuela',
  'GDP_Access': 189076.5,
  'VisaRequirement': 'Visa not Required',
  'VisaTemplate': 'yes'},
 {'Country': 'Vietnam',
  'GDP_Access': 110204.0,
  'VisaRequirement': 'Electronic Visa',
  'VisaTemplate': 'yes2'},
 {'Country': 'Yemen',
  'GDP_Access': 6604.4,
  'VisaRequirement': 'Visa is required',
  'VisaTemplate': 'no'},
 {'Country': 'Zambia',
  'GDP_Access': 17852.8,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'},
 {'Country': 'Zimbabwe',
  'GDP_Access': 11973.5,
  'VisaRequirement': 'Visa on Arrival',
  'VisaTemplate': 'Optional'}]